name: reschool
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+6

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  crypto: ^3.0.7
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.0
  provider: ^6.1.5+1
  intl: any
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  permission_handler: ^11.0.0
  share_plus: ^10.0.0
  image_picker: ^1.0.0
  file_picker: ^8.0.0
  mime: ^2.0.0
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^10.0.0
  home_widget: ^0.8.1
  workmanager: ^0.5.2
  pasteboard: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/devices.json
    - assets/icon.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"